name: continuous integration pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x86, x64]
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: false

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: publish
      run: dotnet publish -r win-x64 --self-contained -o publish -c Release
    
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: invoice-generator
        path: ${{ github.workspace }}/publish/*